### ISSUE TITLE
Spectre language

### ISSUE THREAD

**Issue by fgr1986** [leoheck/sublime-spice#1]
Hello, 

I have seen that spectre language support might have a bug:
whenever you put a math expression including a multiplication, in the sintax highlight it appears as a SPICE comment.
Example:

```
     i=i( Rtemp )*v( in_e, out_e )
```

**Comment by leoheck** [comment]
I just updated the code now. Check it out.

**Comment by fgr1986** [comment]
Nice! Thanks!
