### ISSUE TITLE
Comment wrongly interpreted

### ISSUE THREAD

**Issue by MaJerle** [leoheck/sublime-spice#2]
Hello,

when using this syntax highlighter and using MULTIPLY operation inside spice, comments are interpretted by highlighter, on image below.

http://screencloud.net/v/Dp7n

**Comment by leoheck** [comment]
Hi @MaJerle I know this issue but I don't know how to solve since I want enable the coments for each line. You can workaround this using quotes for your expression like this:

```
r1 1 4 'z0 * (k+1)/(k-1)'
```

**Comment by MaJerle** [comment]
You should detect if {}() are opened before saying "we are comment".
I think you don't have other choice.

**Comment by leoheck** [comment]
Are you saing that espressions need to be inside `{ expr }` or `( expr )` ?
I thought the only accepted form was: `" expr "` and `' expr '`.

This is a good start, I will give a look tonight. However, you can use `" expr "` and `' expr '` for now.

**Comment by MaJerle** [comment]
Comments are allowed only if everything is closed, so all brackets and
similar.
This could be a start. If you open a brackets for equation, then you can't
make a comment.

## 

Tilen Majerle
Tušev Dol 11
8340 Črnomelj
Slovenia
www: http://majerle.eu
e-mail: tilen@majerle.eu
skype: tjuln10

2015-11-24 16:47 GMT+01:00 Leandro Heck notifications@github.com:

**Comment by leoheck** [comment]
I think it is better now!
