### ISSUE TITLE
The variables are also getting treated as comments.

### ISSUE THREAD

**Issue by davik** [leoheck/sublime-spice#3]
See the line number 39.

![updated](https://cloud.githubusercontent.com/assets/1523644/14765765/38622888-0a0e-11e6-9b8c-de77072b12c8.png)

**Comment by leoheck** [comment]
I know... but I always put the equation between `" "` instead of `{ }` or `( )`. But you are right, this should be improved. Can you help me to do that?

**Comment by davik** [comment]
I have no idea about this. But I know people who have worked with Sublime-Plugins. I will forward the issue to them. 

The previous issue can be solved by, Comments should start with "**"(double star). By this compiler will never have the problem to distinguish Multiplication and Comment but Sublime can properly distinguish them. (Just proposing a method, no idea if it actually can be implemented.)

**Comment by leoheck** [comment]
Good! I just started this project to highlight comments. And this becomes pretty awesome.

**Comment by leoheck** [comment]
Hi @davik , give a try in the new changes.
