### ISSUE TITLE
Issue with `*` 

### ISSUE THREAD

**Issue by chinnichaitanya** [leoheck/sublime-spice#5]
`*` is for comments in SpiceOpus but when I have a command like,
`plot 10*v(1) v(4) xlabel t[s] ylabel '10*Input, Output [V]'`, 
the part `v(1) v(4) xlabel t[s] ylabel '10*Input, Output [V]` is taken as comment whereas it is not.

**Comment by leoheck** [comment]
The problem seems to be with `10*v(1)` try to put it between apostrophes like you did in:

```
'10*Input, Output [V]'
```

Equations should be inside of `( ) { } " " ' '`

**Comment by chinnichaitanya** [comment]
@leoheck Thanks for the help. The problem is solved after I've included `10*v(1)` inside `{ }`.
It would be great to include it in `README.md`

**Comment by amccaugh** [comment]
Is it possible to change this so that `*` only produces a comment when it's at the beginning of a line (or after newline + whitespace/tabs)?  I believe the SPICE specification does not have  `*` as a mid-line comment operator

See for instance:
http://electronics.stackexchange.com/questions/108667/how-to-comment-at-the-end-of-a-command-in-ltspice

**Comment by leoheck** [comment]
Ok @amccaugh, I could do that but what is the problem with ``*`` in the middle of the line? As I know, expressions with ``*`` should be inside one of these characters: ``( ), { }, " ", ' '``. However, there are many spice simulators. I have access to Cadence spectre, Synopsys hspice and SpiceOpus. Do you use LTspice? Also, the main problem is to handle all of these simulators at once when they don't play the same rules. Can you share some of your spice files?

**Comment by amccaugh** [comment]
Yes, I'm using LTSpice, which I realize now doesn't require brackets or anything else surrounding the equation, so this might be a special case.  As a followup though, is there a reason the function syntax highlighting disappears inside the curly brackets?  I do like the look of the purple-highlighted functions, but they seem to disappear once I put my curly brackets in place:

![image](https://cloud.githubusercontent.com/assets/2075083/21270620/a5186e22-c374-11e6-9d0e-09992e836c48.png)

**Comment by leoheck** [comment]
Today I changed the behavior you told about comments and I also removed this behavior you pointed just now. You have to wait for the updates if you use package control.

**Comment by amccaugh** [comment]
Thanks @leoheck !
